server:
  port: 8088
spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
#    #url: ${SPRING_DATASOURCE_URL:jdbc:mysql://ubuntu-server-01.local:3399/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ${MYSQL_ROOT_PASSWORD:Abc123456789@}
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 970079410939-28ctr6vgasfm4qj2p0nlorainm558e5i.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
#            redirect-uri: http://localhost:8088/api/v1/auth/google/code


#            redirect-uri: http://localhost:8088/api/v1/auth/google/code


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ecommerce5106@gmail.com
    password: kmyg vooa oild stsj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      use-redis-cache: false
      host: localhost
      port: 6379
api:
  prefix: /api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
